# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'idrawjs/idraw'
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm config set registry https://registry.yarnpkg.com/
      # - run: npm install
      - run: npm install --global pnpm
      - run: pnpm i
      - run: npm run beforetest
      - run: npm run cover
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #     files: /home/runner/work/idraw/idraw/reports/clover.xml # optional
      #     flags: unittests # optional
      #     name: codecov-umbrella # optional
      #     fail_ci_if_error: true # optional (default = false)
      #     verbose: true # optional (default = false)
